name: Post Welcome Comment
on:
  push:
jobs:
  build:
    name: Post Weclome comment
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello World"
    
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_URL: ${{ github.event.pull_request.html_url }}
